### PR TITLE
[releases/2.0]: Cherry-pick 'Add .serviceignore files to the examples'

### PR DESCRIPTION
**Pull request by dixonjoel**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/measurement-services-python/blob/main/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Cherry-pick "Add .serviceignore files to the examples" commit from main.

### Why should this Pull Request be merged?

Needed for releases / 2.0

### What testing has been done?

None - straight cherry-pick

### CODE REVIEW

**Comment by bkeryan** [comment]
Does this belong in 2.0? @nick-beer wrote this in https://github.com/ni/measurement-plugin-python/pull/784

> Note
> This PR should not be completed prior to the upcoming release of Plug-in Library.

**Comment by nick-beer** [comment]
> Does this belong in 2.0? @nick-beer wrote this in #784
> 
> > Note
> > This PR should not be completed prior to the upcoming release of Plug-in Library.

@bkeryan - Yes, I believe it does.  I talked with Joel about this offline.  I just want to make sure it goes with whatever we just completed for C2.

**Review by bkeryan — APPROVED** [review]

**Comment by dixonjoel** [comment]
@bkeryan I don't know why the checks are not running. I'm going to create a new PR with this branch.

**Comment by dixonjoel** [comment]
Not running checks

**Pull request closed without merging**
